from __future__ import annotations

from pathlib import Path

import pytest

from zerogravity.parsers.base import DependencyType
from zerogravity.parsers.node_parser import NodeParser


def test_can_parse_with_package_json(node_project_path: Path):
    parser = NodeParser()
    assert parser.can_parse(node_project_path) is True


def test_can_parse_without_package_json(tmp_path: Path):
    parser = NodeParser()
    assert parser.can_parse(tmp_path) is False


def test_parse_dependencies(node_project_path: Path):
    parser = NodeParser()
    manifest = parser.parse(node_project_path)
    deps = {d.name: d for d in manifest.dependencies}
    assert "express" in deps
    assert deps["express"].dep_type == DependencyType.PRODUCTION
    assert deps["jest"].dep_type == DependencyType.DEVELOPMENT
    assert deps["react"].dep_type == DependencyType.PEER
    assert deps["fsevents"].dep_type == DependencyType.OPTIONAL


def test_parse_engine_constraints(node_project_path: Path):
    parser = NodeParser()
    manifest = parser.parse(node_project_path)
    assert manifest.engine_constraints["node"] == ">=18.0.0"


def test_parse_lockfile_detection(node_project_path: Path):
    parser = NodeParser()
    manifest = parser.parse(node_project_path)
    assert manifest.lockfile_present is True
    assert manifest.lockfile_path == node_project_path / "package-lock.json"


def test_parse_resolved_versions(node_project_path: Path):
    parser = NodeParser()
    manifest = parser.parse(node_project_path)
    deps = {d.name: d for d in manifest.dependencies}
    assert deps["express"].resolved_version == "4.18.2"


def test_parse_empty_dependencies(tmp_path: Path):
    pkg = tmp_path / "package.json"
    pkg.write_text('{"name": "empty"}')
    parser = NodeParser()
    manifest = parser.parse(tmp_path)
    assert len(manifest.dependencies) == 0


def test_parse_malformed_json(tmp_path: Path):
    pkg = tmp_path / "package.json"
    pkg.write_text('{malformed')
    parser = NodeParser()
    with pytest.raises(ValueError):
        parser.parse(tmp_path)


def test_parse_yarn_lock_multi_selector(tmp_path: Path):
    """
    Real yarn.lock commonly groups several range selectors that resolved to
    the same version under one entry, e.g. two @babel/core requirements
    from different dependencies. The parser must still find the version.
    """
    (tmp_path / "package.json").write_text(
        '{"name": "yarn-app", "dependencies": {"lodash": "^4.17.21"}}'
    )
    (tmp_path / "yarn.lock").write_text(
        '# THIS IS AN AUTOGENERATED FILE\n'
        '# yarn lockfile v1\n\n'
        '"@babel/core@^7.0.0", "@babel/core@^7.12.3":\n'
        '  version "7.20.0"\n'
        '  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.0.tgz"\n\n'
        'lodash@^4.17.21:\n'
        '  version "4.17.21"\n'
        '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"\n'
    )
    manifest = NodeParser().parse(tmp_path)
    deps = {d.name: d for d in manifest.dependencies}

    assert deps["lodash"].resolved_version == "4.17.21"
    assert "@babel/core" in deps
    assert deps["@babel/core"].resolved_version == "7.20.0"
    assert deps["@babel/core"].metadata.get("transitive") is True


def test_parse_pnpm_lock_v9_format(tmp_path: Path):
    """
    pnpm 9/10/11 write 'packages' keys as 'name@version' or
    '@scope/name@version' with no leading slash -- the pre-v9 format this
    parser originally assumed. Confirms the current format actually parses.
    """
    (tmp_path / "package.json").write_text(
        '{"name": "pnpm-app", "dependencies": {"lodash": "^4.17.21"}}'
    )
    (tmp_path / "pnpm-lock.yaml").write_text(
        "lockfileVersion: '9.0'\n"
        "settings:\n"
        "  autoInstallPeers: true\n"
        "importers:\n"
        "  .:\n"
        "    dependencies:\n"
        "      lodash:\n"
        "        specifier: ^4.17.21\n"
        "        version: 4.17.21\n"
        "packages:\n"
        "  lodash@4.17.21:\n"
        "    resolution: {integrity: sha512-xxx}\n"
        "  '@babel/code-frame@7.27.1':\n"
        "    resolution: {integrity: sha512-yyy}\n"
        "  ansi-regex@5.0.1:\n"
        "    resolution: {integrity: sha512-zzz}\n"
        "  '@hono/zod-validator@0.4.3(hono@4.7.6)(zod@3.24.2)':\n"
        "    resolution: {integrity: sha512-www}\n"
    )
    manifest = NodeParser().parse(tmp_path)
    deps = {d.name: d for d in manifest.dependencies}

    assert deps["lodash"].resolved_version == "4.17.21"
    assert deps["@babel/code-frame"].resolved_version == "7.27.1"
    assert deps["@babel/code-frame"].metadata.get("transitive") is True
    assert deps["ansi-regex"].resolved_version == "5.0.1"
    # peer-suffixed key still resolves to the base name/version
    assert deps["@hono/zod-validator"].resolved_version == "0.4.3"


def test_parse_pnpm_lock_legacy_format(tmp_path: Path):
    """Pre-v6 pnpm-lock.yaml used '/name/version:' keys -- still supported."""
    (tmp_path / "package.json").write_text(
        '{"name": "pnpm-app", "dependencies": {"lodash": "^4.17.21"}}'
    )
    (tmp_path / "pnpm-lock.yaml").write_text(
        "lockfileVersion: 5.4\n"
        "packages:\n"
        "  /lodash/4.17.21:\n"
        "    dev: false\n"
    )
    manifest = NodeParser().parse(tmp_path)
    deps = {d.name: d for d in manifest.dependencies}
    assert deps["lodash"].resolved_version == "4.17.21"


def test_parse_pnpm_lock_malformed_yaml_does_not_crash(tmp_path: Path):
    (tmp_path / "package.json").write_text('{"name": "pnpm-app"}')
    (tmp_path / "pnpm-lock.yaml").write_text(":\n  - not: [valid yaml")
    manifest = NodeParser().parse(tmp_path)
    assert manifest.lockfile_present is True


@pytest.mark.parametrize(
    "key,expected",
    [
        ("lodash@4.17.21", ("lodash", "4.17.21")),
        ("@babel/code-frame@7.27.1", ("@babel/code-frame", "7.27.1")),
        ("/lodash/4.17.21", ("lodash", "4.17.21")),
        ("/@rushstack/n/3.0.0", ("@rushstack/n", "3.0.0")),
        ("/lodash@4.17.21", ("lodash", "4.17.21")),
        ("react-dom@18.2.0(react@18.2.0)", ("react-dom", "18.2.0")),
        ("foo/1.0.0_@rushstack+m@1.0.0", ("foo", "1.0.0")),
        ("", None),
        ("no-version-here", None),
    ],
)
def test_parse_pnpm_package_key(key, expected):
    from zerogravity.parsers.node_parser import _parse_pnpm_package_key
    assert _parse_pnpm_package_key(key) == expected


@pytest.mark.parametrize(
    "selector,expected_name",
    [
        ("lodash@^4.17.21", "lodash"),
        ('"lodash@^4.17.21"', "lodash"),
        ("@babel/core@^7.0.0", "@babel/core"),
        ('"@babel/core@^7.12.3"', "@babel/core"),
    ],
)
def test_yarn_selector_name(selector, expected_name):
    from zerogravity.parsers.node_parser import _yarn_selector_name
    assert _yarn_selector_name(selector) == expected_name
